### PR TITLE
Initial refactoring of Nengo SpiNNaker

### PR DESCRIPTION
**Pull request by mundya**
Almost happy with this, just some strange results when testing.
Thoughts?

Done:
- Reorganise Builder
- Removed `*Data` classes and wrapped their functionality into the `*Vertex` classes
- Put some structure in place for Rx and Tx (the decoder and node bins for example)

### CODE REVIEW

**Comment by mundya** [comment]
@tcstewar I'm now happy that the Python is all working correctly.  The C I'm less happy with, are there sufficient `dt`s floating around the place?

Do you mind testing?
Cheers!

**Comment by tcstewar** [comment]
Hi -- sorry I'm behind on this stuff -- it's been a bit crazy here.  I should have a chance to test this tomorrow....

**Comment by mundya** [comment]
No problem, sorry for nagging!

I'm beginning to think that my concerns over the C are just the result of FP and fixed time intervals, I'm going to implement a variant of your LFSR/Refractory mod and see if that makes a noticeable difference.

**Comment by mundya** [comment]
I'm merging as this is almost definitely where we should continue development.  The bodge to `rx` components will hopefully be unnecessary shortly :worried:

**Pull request merged**
