### PR TITLE
Tx to pc

### PR DESCRIPTION
**Pull request by tcstewar**
I think I'm happy with this, but I'd like to know whether the way I'm getting the keys is the recommended approach (the changes to ensemble_vertex and decoder_edge).

### CODE REVIEW

**Comment by mundya** [comment]
That seems mostly fine.  Some comments are:
1. We probably don't want `port=` hard coded in the long run
2. We need to investigate using the PACMAN support for informing SpiNNaker that we want things sent to IPTAG1 to end up on the host at the given port (see the `scp` module)

There is some work going on to ensure that the host and SpiNNaker are synchronised.  The issue here is that you're only listening for _n_ seconds but there may be _m_ of those seconds where SpiNNaker is internally synchronising and starting up.  I'll check with people what the solution being implemented is.

Longer term, I'd like to clarify our Tx protocol (as in #9).

I'm happy to merge provided we address those issues later.

**Comment by tcstewar** [comment]
> Some comments are:
> 
> We probably don't want port= hard coded in the long run
> We need to investigate using the PACMAN support for informing SpiNNaker that we want things sent to IPTAG1 to end up on the host at the given port (see the scp module)

Definitely.  I was going to raise those as a separate issue, since they seem somewhat related (the port has to be the same, anyway)

I was also going to put in a more general issue of is there any way that the Builder can kill what's going on on the board, so it doesn't have to get reset every time we load something on it....  but that might be a much bigger issue....  ;)

**Comment by mundya** [comment]
Yes, we can kill... somewhere in the SCP module.  You can also kill from ybug (for testing purposes), `app_kill`.  We seem to have some synchronisation options that are stopping an app_kill followed by a new load working for me at the moment, I'll chase these down next week.

**Comment by mundya** [comment]
Can I suggest we close this as most of the work has been superseded by the `general-io` branch. Sorry!

**Comment by tcstewar** [comment]
Sounds good to me.  :)

**Pull request closed without merging**
